version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb

  backend:
    build:
      context: .
      args:
        APP_TARGET: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma db seed &&
      pnpm run dev
      "