version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb

  backend:
    build:
      context: .
      args:
        APP_TARGET: ${APP_TARGET}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma db seed &&
      pnpm run dev
      "
