name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install

      # Ensure shared types are built before typecheck/test
      - run: pnpm --filter shared build

      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
