name: Deploy to Main

on:
  push:
    branches: [main]

jobs:
  prisma-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter backend prisma generate
      - run: pnpm --filter backend prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
